general_params:
  T_stop: 20                # Modelling time(s)
  sampling_frequency: 100   # Sampling frequency(Hz)
regulator_params:
  Kp: 8.0                   # Proportional gain
  Ki: 0.03                  # Integral gain
  max_action: 48.0          # Max. output of regulator(Volts)
  min_action: -48.0         # Min. output of regulator(Volts)
imitation_model_params:     
  Noise_amplitude: 0.01     # Amplitude of gauss noise in feedback loop
  Gain: 0.5                 # Decay factor of exponent
  Initial_cond: 0.0         # Initial condition
feedback_filter_params:
  pass_frequency: 2.5       # Feedback filter pass frequency(Hz)
  
